<a href="https://colab.research.google.com/github/masrufjaman/numPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load NumPy

In [2]:
import numpy as np

##Basics

In [ ]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
# Get Total Size
a.size*a.itemsize

12

In [ ]:
a.nbytes

12

## Accessing/Changing specific elements, rows, columns etc

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r,c]
a[1, 2]

10

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex;stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,4] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


In [ ]:
a[:,1] = 5
print(a)

[[ 1  5  3  4  5  6  7]
 [ 8  5 10 11 20 13 14]]


In [ ]:
a[:,1] = [1,2]
print(a)

[[ 1  1  3  4  5  6  7]
 [ 8  2 10 11 20 13 14]]


* 3-d examples

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[1,0,1]

6

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [4]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [7]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [9]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.29755544, 0.29186627, 0.05049813],
        [0.27590024, 0.21034061, 0.3726689 ]],

       [[0.75166854, 0.81605042, 0.21510421],
        [0.31585941, 0.68052973, 0.49652063]],

       [[0.22688379, 0.09441508, 0.37955752],
        [0.60499113, 0.75100352, 0.635649  ]],

       [[0.22819227, 0.91181829, 0.00693432],
        [0.38481561, 0.5106479 , 0.57001475]]])

In [13]:
# Random Integer values
np.random.randint(2,8, size=(3,3))

array([[3, 4, 7],
       [5, 3, 5],
       [4, 7, 6]])

In [14]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***Be careful when copying arrays!!!***

In [21]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]
