<a href="https://colab.research.google.com/github/masrufjaman/numPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load NumPy

In [2]:
import numpy as np

##Basics

In [8]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int32')

In [12]:
# Get Size
a.itemsize

4

In [13]:
# Get Total Size
a.size*a.itemsize

12

In [16]:
a.nbytes

12

## Accessing/Changing specific elements, rows, columns etc

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# Get a specific element [r,c]
a[1, 2]

10

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex;stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [27]:
a[0, 1:-1:2]

array([2, 4, 6])

In [28]:
a[1,4] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


In [29]:
a[:,1] = 5
print(a)

[[ 1  5  3  4  5  6  7]
 [ 8  5 10 11 20 13 14]]


In [31]:
a[:,1] = [1,2]
print(a)

[[ 1  1  3  4  5  6  7]
 [ 8  2 10 11 20 13 14]]


* 3-d examples

In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (work outside in)
b[1,0,1]

6

In [36]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [39]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
